development:
  ubuntu:
    rt_table_path: '/etc/iproute2/rt_tables'
    config_file_path: 'config/sample.json'

test:
  ubuntu:
    rt_table_table: 'spec/rt_tables'
    config_file_path: 'spec/config/sample.json'
