development:
  ubuntu:
    rt_table_path: '/etc/iproute2/rt_tables'
    config_file_path: 'config/configuration.json'

test:
  ubuntu:
    rt_table_path: './spec/rt_tables'
    config_file_path: './spec/config/configuration.json'
